### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nemoNoboru** [Narnach/rails_analyzer#1]
not working. Error:
RailsAnalyzer
Analyzes the following Rails log files:
  log/production.log
Generating time-based reports
/home/fvieira/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/Narnach-rails_analyzer-0.2.2/lib/time_stats.rb:20:in `block in parse_files': undefined method`map' for #String:0x007f496fb558f0 (NoMethodError)
    from /home/fvieira/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/Narnach-rails_analyzer-0.2.2/lib/time_stats.rb:18:in `each'
    from /home/fvieira/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/Narnach-rails_analyzer-0.2.2/lib/time_stats.rb:18:in`parse_files'
    from /home/fvieira/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/Narnach-rails_analyzer-0.2.2/lib/time_stats.rb:13:in `generate'
    from /home/fvieira/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/Narnach-rails_analyzer-0.2.2/lib/rails_analyzer.rb:18:in`generate_reports'
    from /home/fvieira/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/Narnach-rails_analyzer-0.2.2/bin/rails_analyzer:5:in `<top (required)>'
    from /home/fvieira/.rbenv/versions/2.2.3/bin/rails_analyzer:23:in`load'
    from /home/fvieira/.rbenv/versions/2.2.3/bin/rails_analyzer:23:in `<main>'

**Comment by Narnach** [comment]
Holy moly! Thanks for the feedback. I forgot I still even had this, because it's been 8 years since I worked on this.

This project was designed to work on Ruby 1.8 and Rails 1.2. Both Ruby's core classes and Rails' log format have changed since then. It looks like the code tries to call `String#map`, which relies on `String#each`, which was removed around Ruby 1.9 or 2.0, in favour of method such as `String#each_line` and `String#each_byte`.

I don't use it anymore, but if you want to submit a Pull Request I'd be happy to accept it for the benefit of those who do want to use it.
